[package]
name = "parser_reworked"
version = "0.1.0"
authors = ["vera"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.0"
frame-metadata = "15.0.0"
hex = "0.4.3"
num-bigint = "0.4.3"
parity-scale-codec = {version = "3.1.5", features = ["derive", "bit-vec"]}
scale-info = "2.1.2"
sp-arithmetic = {version = "5.0.0", default-features = false}
sp-core = {version = "6.0.0", default-features = false, features = ["full_crypto"]}
sp-runtime = "6.0.0"

[features]
default = ["standalone"]
standalone = []

[lib]
name = "parser_reworked"
crate-type = ["lib"]
